name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify Node.js version
      - run: npm install
      - run: npm run build
      - run: git config --global user.name 'Your Name'
      - run: git config --global user.email 'your-email@example.com'
      - run: npm run deploy  # Assuming you have a deploy script configured
